This notebook implements a traditional machine learning model using KNN to classify car damage severity into minor, moderate, and severe. The dataset is made by Prajwal Bhamere and comes from https://www.kaggle.com/datasets/prajwalbhamere/car-damage-severity-dataset/data.

In [2]:
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import numpy as np

2025-11-16 17:40:27.915548: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-11-16 17:40:28.038883: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-16 17:40:33.429040: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-11-16 17:40:51.061855: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To tur

In [12]:
datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=25,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1,
    brightness_range=[0.7, 1.3],
    horizontal_flip=True,
    fill_mode='nearest'
)

train_it = datagen.flow_from_directory( '../dataset/train', 
                                           target_size=(224,224), 
                                           color_mode='grayscale', 
                                           batch_size=1,
                                           class_mode="categorical",)

valid_it = datagen.flow_from_directory( '../dataset/val', 
                                           target_size=(224,224), 
                                           color_mode='grayscale', 
                                           batch_size=1,
                                           class_mode="categorical",)



Found 1383 images belonging to 3 classes.


Found 248 images belonging to 3 classes.


In [13]:
X = []
y = []
batch_index = 0

while batch_index <= train_it.batch_index:
    #iterate through the training data and build a single array
    x_temp, y_temp = next(train_it)
    X.append(x_temp[0])
    y.append(y_temp[0])
    batch_index = batch_index + 1

X_train = np.array(X)
X_train = X_train.reshape(X_train.shape[0], -1)
y_train = np.array(y)
y_train = np.argmax(y_train, axis=1)

X = []
y = []
batch_index = 0

while batch_index <= valid_it.batch_index:
    #iterate through the test data to build a single array
    x_temp, y_temp = next(valid_it)
    X.append(x_temp[0])
    y.append(y_temp[0])
    batch_index = batch_index + 1

X_test = np.array(X)
X_test = X_test.reshape(X_test.shape[0], -1)
y_test = np.array(y)
y_test = np.argmax(y_test, axis=1)

In [17]:
def run_knn(X_train, y_train, X_test, y_test, k=3):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    print('Accuracy of K-NN classifier on training set: {:.2f}'
         .format(knn.score(X_train, y_train)))
    print('Accuracy of K-NN classifier on test set: {:.2f}'
         .format(knn.score(X_test, y_test)))
    pred = knn.predict(X_test)
    print(confusion_matrix(y_test, pred))

In [18]:
run_knn(X_train, y_train, X_test, y_test)

Accuracy of K-NN classifier on training set: 0.53
Accuracy of K-NN classifier on test set: 0.38
[[73  6  3]
 [56 11  8]
 [63 17 11]]
