This notebook implements a traditional machine learning model using KNN to classify car damage severity into minor, moderate, and severe. The dataset is made by Prajwal Bhamere and comes from https://www.kaggle.com/datasets/prajwalbhamere/car-damage-severity-dataset/data.

In [1]:
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import numpy as np

In [2]:
datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=25,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1,
    brightness_range=[0.7, 1.3],
    horizontal_flip=True,
    fill_mode='nearest'
)

train_it = datagen.flow_from_directory( '../dataset/train', 
                                           target_size=(224,224), 
                                           color_mode='grayscale', 
                                           batch_size=1,
                                           class_mode="categorical",)

valid_it = datagen.flow_from_directory( '../dataset/val', 
                                           target_size=(224,224), 
                                           color_mode='grayscale', 
                                           batch_size=1,
                                           class_mode="categorical",)



Found 1383 images belonging to 3 classes.
Found 248 images belonging to 3 classes.


In [3]:
X = []
y = []
batch_index = 0

while batch_index <= train_it.batch_index:
    #iterate through the training data and build a single array
    x_temp, y_temp = next(train_it)
    X.append(x_temp[0])
    y.append(y_temp[0])
    batch_index = batch_index + 1

X_train = np.array(X)
X_train = X_train.reshape(X_train.shape[0], -1)
y_train = np.array(y)
y_train = np.argmax(y_train, axis=1)

X = []
y = []
batch_index = 0

while batch_index <= valid_it.batch_index:
    #iterate through the test data to build a single array
    x_temp, y_temp = next(valid_it)
    X.append(x_temp[0])
    y.append(y_temp[0])
    batch_index = batch_index + 1

X_test = np.array(X)
X_test = X_test.reshape(X_test.shape[0], -1)
y_test = np.array(y)
y_test = np.argmax(y_test, axis=1)

In [4]:
def run_knn(X_train, y_train, X_test, y_test, k=3):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    print('Accuracy of K-NN classifier on training set: {:.2f}'
         .format(knn.score(X_train, y_train)))
    print('Accuracy of K-NN classifier on test set: {:.2f}'
         .format(knn.score(X_test, y_test)))
    pred = knn.predict(X_test)
    print(confusion_matrix(y_test, pred))

In [5]:
run_knn(X_train, y_train, X_test, y_test)

Accuracy of K-NN classifier on training set: 0.54
Accuracy of K-NN classifier on test set: 0.35
[[68 10  4]
 [66  6  3]
 [69 10 12]]


In [6]:
k_vals = [3, 5, 7, 9, 11, 15, 21]
for k in k_vals:
    print(f"K = {k}")
    run_knn(X_train, y_train, X_test, y_test, k=k)

K = 3
Accuracy of K-NN classifier on training set: 0.54
Accuracy of K-NN classifier on test set: 0.35
[[68 10  4]
 [66  6  3]
 [69 10 12]]
K = 5
Accuracy of K-NN classifier on training set: 0.46
Accuracy of K-NN classifier on test set: 0.34
[[69 10  3]
 [66  7  2]
 [72 10  9]]
K = 7
Accuracy of K-NN classifier on training set: 0.43
Accuracy of K-NN classifier on test set: 0.37
[[76  5  1]
 [66  7  2]
 [71 11  9]]
K = 9
Accuracy of K-NN classifier on training set: 0.42
Accuracy of K-NN classifier on test set: 0.35
[[74  6  2]
 [68  5  2]
 [74 10  7]]
K = 11
Accuracy of K-NN classifier on training set: 0.40
Accuracy of K-NN classifier on test set: 0.34
[[76  5  1]
 [69  3  3]
 [76 10  5]]
K = 15
Accuracy of K-NN classifier on training set: 0.39
Accuracy of K-NN classifier on test set: 0.35
[[74  6  2]
 [68  5  2]
 [75  7  9]]
K = 21
Accuracy of K-NN classifier on training set: 0.38
Accuracy of K-NN classifier on test set: 0.35
[[76  3  3]
 [72  3  0]
 [75  9  7]]
